from pathlib import Path

path = Path('salesboard/app/app.js')
text = path.read_text(encoding='utf-8')

old = """  async function signInWithGoogle() {\n    const button = $('#google-auth-button');\n    if (!supabaseClient) return;\n    setButtonLoading(button, true, 'Abrindo Google...');\n    setAuthMessage('');\n    try {\n      sessionStorage.setItem('salesboard_oauth_intent', JSON.stringify({ plan: requestedPlan, billing: billingCycle, createdAt: Date.now() }));\n      const { data, error } = await supabaseClient.auth.signInWithOAuth({\n        provider: 'google',\n        options: { redirectTo: appBaseUrl('oauth=google'), skipBrowserRedirect: true, queryParams: { prompt: 'select_account' } }\n      });\n      if (error) throw error;\n      if (!data?.url) throw new Error('Não foi possível iniciar o login com Google.');\n      location.assign(data.url);\n    } catch (error) {\n      setButtonLoading(button, false);\n      setAuthMessage(authErrorMessage(error), true);\n    }\n  }"""

new = """  async function googleProviderAvailable() {\n    try {\n      const response = await fetch(`${publicConfig.supabaseUrl}/auth/v1/settings`, {\n        headers: { apikey: publicConfig.supabasePublishableKey, Accept: 'application/json' },\n        cache: 'no-store'\n      });\n      if (!response.ok) return null;\n      const settings = await response.json();\n      return settings?.external?.google === true;\n    } catch (error) {\n      console.warn('Não foi possível verificar o provedor Google.', error);\n      return null;\n    }\n  }\n\n  async function signInWithGoogle() {\n    const button = $('#google-auth-button');\n    if (!supabaseClient) return;\n    setButtonLoading(button, true, 'Verificando Google...');\n    setAuthMessage('');\n    try {\n      const available = await googleProviderAvailable();\n      if (available !== true) {\n        const message = available === false\n          ? 'O login com Google ainda não está habilitado. Use e-mail e senha por enquanto; estamos finalizando essa configuração.'\n          : 'Não foi possível verificar o login com Google agora. Tente novamente ou use e-mail e senha.';\n        setAuthMessage(message, true);\n        return;\n      }\n\n      setButtonLoading(button, true, 'Abrindo Google...');\n      sessionStorage.setItem('salesboard_oauth_intent', JSON.stringify({ plan: requestedPlan, billing: billingCycle, createdAt: Date.now() }));\n      const { data, error } = await supabaseClient.auth.signInWithOAuth({\n        provider: 'google',\n        options: { redirectTo: appBaseUrl('oauth=google'), skipBrowserRedirect: true, queryParams: { prompt: 'select_account' } }\n      });\n      if (error) throw error;\n      if (!data?.url) throw new Error('Não foi possível iniciar o login com Google.');\n      location.assign(data.url);\n    } catch (error) {\n      setAuthMessage(authErrorMessage(error), true);\n    } finally {\n      setButtonLoading(button, false);\n    }\n  }"""

if old not in text:
    raise SystemExit('Google OAuth marker not found; refusing partial patch')

text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
print('Google provider guard applied')
