const KEYS={sales:'salesboard.sales.v1',settings:'salesboard.settings.v1'};
const defaults={appName:'SalesBoard',planName:'SalesBoard Pro',monthlyPrice:49.9,monthlyGoal:15000,currency:'BRL',defaultTicket:250,planDescription:'Dashboard completo para acompanhar suas vendas e clientes.'};
const ago=d=>{const x=new Date();x.setDate(x.getDate()-d);return x.toISOString().slice(0,10)};
let settings=JSON.parse(localStorage.getItem(KEYS.settings)||'null')||defaults;
let sales=JSON.parse(localStorage.getItem(KEYS.sales)||'null')||[
{id:crypto.randomUUID(),customer:'Marina Souza',product:'Consultoria Premium',amount:890,date:ago(2),status:'Pago'},
{id:crypto.randomUUID(),customer:'Lucas Almeida',product:'Plano Mensal',amount:349.9,date:ago(5),status:'Pago'},
{id:crypto.randomUUID(),customer:'Ana Clara',product:'Setup Comercial',amount:1250,date:ago(9),status:'Pago'},
{id:crypto.randomUUID(),customer:'Carlos Lima',product:'Plano Mensal',amount:349.9,date:ago(14),status:'Pendente'},
{id:crypto.randomUUID(),customer:'Oficina Delta',product:'Licença anual',amount:2400,date:ago(35),status:'Pago'},
{id:crypto.randomUUID(),customer:'Studio Nove',product:'Setup Comercial',amount:980,date:ago(66),status:'Cancelado'}];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),save=()=>{localStorage.setItem(KEYS.sales,JSON.stringify(sales));localStorage.setItem(KEYS.settings,JSON.stringify(settings))};
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:settings.currency}).format(Number(v||0));
function setView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#pageTitle').textContent={dashboard:'Dashboard',sales:'Vendas',customers:'Clientes',billing:'Assinatura',settings:'Configurações'}[id]||'Dashboard'}
$$('[data-view], [data-view-trigger]').forEach(b=>b.onclick=()=>setView(b.dataset.view||b.dataset.viewTrigger));
function renderSettings(){settings={...defaults,...settings};$('#brandName').textContent=settings.appName;$('#goalLabel').textContent='Meta: '+money(settings.monthlyGoal);$('#planName').textContent=settings.planName;$('#planDescription').textContent=settings.planDescription;$('#planPrice').textContent=money(settings.monthlyPrice)+'/mês';Object.entries(settings).forEach(([k,v])=>{const el=$(`[name="${k}"]`);if(el)el.value=v})}
function renderMetrics(){const paid=sales.filter(s=>s.status==='Pago'),sum=paid.reduce((a,s)=>a+Number(s.amount),0);$('#paidRevenue').textContent=money(sum);$('#salesCount').textContent=sales.length;$('#avgTicket').textContent=money(paid.length?sum/paid.length:0);$('#goalProgress').textContent=Math.min(100,Math.round(sum/settings.monthlyGoal*100))+'%'}
function renderTables(){const rows=[...sales].sort((a,b)=>b.date.localeCompare(a.date));$('#recentSales').innerHTML=rows.slice(0,8).map(s=>`<tr><td>${s.customer}</td><td>${s.product}</td><td>${money(s.amount)}</td><td>${new Date(s.date+'T00:00').toLocaleDateString('pt-BR')}</td><td><span class="badge ${s.status}">${s.status}</span></td><td><button class="delete" data-del="${s.id}">Excluir</button></td></tr>`).join('');renderAllSales();$$('[data-del]').forEach(b=>b.onclick=()=>{sales=sales.filter(s=>s.id!==b.dataset.del);save();render()})}
function renderAllSales(){const q=($('#search')?.value||'').toLowerCase();$('#allSales').innerHTML=sales.filter(s=>(s.customer+s.product+s.status).toLowerCase().includes(q)).map(s=>`<div class="sale-item"><div><strong>${s.customer}</strong><p>${s.product} • ${money(s.amount)} • ${s.status}</p></div><button class="delete" data-del="${s.id}">Excluir</button></div>`).join('')||'<p>Nenhuma venda encontrada.</p>'}
function renderCustomers(){const map={};sales.forEach(s=>{map[s.customer]??={count:0,total:0,last:s.date};map[s.customer].count++;if(s.status==='Pago')map[s.customer].total+=Number(s.amount);if(s.date>map[s.customer].last)map[s.customer].last=s.date});$('#customersList').innerHTML=Object.entries(map).map(([name,c])=>`<article class="customer-card"><strong>${name}</strong><p>${c.count} venda(s)</p><p>Total pago: ${money(c.total)}</p><p>Última: ${new Date(c.last+'T00:00').toLocaleDateString('pt-BR')}</p></article>`).join('')||'<p>Nenhum cliente cadastrado.</p>'}
function drawChart(){const c=$('#chart'),ctx=c.getContext('2d'),w=c.width=c.offsetWidth*devicePixelRatio,h=c.height=220*devicePixelRatio;ctx.clearRect(0,0,w,h);const now=new Date(),months=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);months.push({key:d.toISOString().slice(0,7),label:d.toLocaleDateString('pt-BR',{month:'short'}),total:0})}sales.filter(s=>s.status==='Pago').forEach(s=>{const m=months.find(x=>x.key===s.date.slice(0,7));if(m)m.total+=Number(s.amount)});const max=Math.max(settings.monthlyGoal,...months.map(m=>m.total),1),gap=w/(months.length*2),bar=gap*.8;ctx.fillStyle='#eef2ff';ctx.fillRect(0,h-(settings.monthlyGoal/max*h),w,2);months.forEach((m,i)=>{const x=gap*(i*2+1),bh=m.total/max*(h-34);ctx.fillStyle='#635bff';ctx.fillRect(x,h-bh-24,bar,bh);ctx.fillStyle='#6b7280';ctx.font=`${12*devicePixelRatio}px system-ui`;ctx.fillText(m.label,x,h-6)})}
function render(){renderSettings();renderMetrics();renderTables();renderCustomers();drawChart()}$('#saleForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);sales.push({id:crypto.randomUUID(),customer:f.get('customer'),product:f.get('product'),amount:Number(f.get('amount')),date:f.get('date'),status:f.get('status')});e.target.reset();e.target.date.value=new Date().toISOString().slice(0,10);save();render()};$('#settingsForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);settings={appName:f.get('appName'),planName:f.get('planName'),monthlyPrice:Number(f.get('monthlyPrice')),monthlyGoal:Number(f.get('monthlyGoal')),currency:f.get('currency'),defaultTicket:Number(f.get('defaultTicket')),planDescription:f.get('planDescription')};save();render();setView('dashboard')};$('#search').oninput=renderAllSales;$('#exportCsv').onclick=()=>{const csv=['Cliente,Produto,Valor,Data,Status',...sales.map(s=>`"${s.customer}","${s.product}",${s.amount},${s.date},${s.status}`)].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='salesboard-vendas.csv';a.click()};$('#checkoutBtn').onclick=async()=>{const msg=$('#checkoutMessage');msg.textContent='Criando checkout...';try{const r=await fetch('/.netlify/functions/create-checkout-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amountCents:Math.round(settings.monthlyPrice*100),currency:settings.currency,planName:settings.planName})});const data=await r.json();if(data.url)location.href=data.url;else throw new Error(data.error||'Checkout indisponível.')}catch(e){msg.textContent=e.message+' Configure Stripe no Netlify ou rode sem cobrança para testar.'}};$('#saleForm').date.value=new Date().toISOString().slice(0,10);render();addEventListener('resize',drawChart);
